# Generated by Django 5.2.12 on 2026-04-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='research_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
